apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
  namespace: ashapp
  labels:
    app: history-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      serviceAccountName: history-sa
      containers:
      - name: history-service
        image: ashwanth01/history-service:latest
        ports:
        - containerPort: 8081
        # --------------------------
        # Resource Requests & Limits
        # --------------------------
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"

