apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor
  namespace: ashapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-monitor
  template:
    metadata:
      labels:
        app: flask-monitor
    spec:
      serviceAccountName: monitor-sa
      containers:
      - name: flask-monitor
        image: ashwanth01/flask-monitor:4bf04e3790c21c47aa13985ff366f495d63bae0e
        ports:
        - containerPort: 6000
        env:
        - name: MYSQL_URI
          value: "mysql+pymysql://root:rootpass@mysql.ashapp.svc.cluster.local:3306/ashdb"
        # --------------------------
        # Resource Requests & Limits
        # --------------------------
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"


